# Global Setttings
title               : "BunkerGames"
description         : "A limited of carefully curation of game servers hosting"
source              : .
collections_dir     : .
plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
port                : 6969
domain              : bunkergames.github.io
url                 : https://bunkergames.github.io
collections:
  servers:
    output: true
    permalink: /:collection/:name
donations:
  paypal:
    text:           Donate      # Button text
    id:             XV8NTFTT9BAM8  # PayPal button ID
